# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [2]:
import numpy as np

In [10]:
my_file = "/content/minutes_n_ingredients.csv"

In [11]:
#Задача 1
a_ld = np.loadtxt(my_file, int, skiprows=1, delimiter=',')
a_ld[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [12]:
#Задача 2
print("Второй столбик:")
print(np.mean(a_ld[:,1]))
print(np.max(a_ld[:,1]))
print(np.min(a_ld[:,1]))
print(np.median(a_ld[:,1]))
print('----------------------')
print("Третий столбик:")
print(np.mean(a_ld[:, 2]))
print(np.min(a_ld[:, 2]))
print(np.max(a_ld[:, 2]))
print(np.median(a_ld[:, 2]))


Второй столбик:
21601.00169
2147483647
0
40.0
----------------------
Третий столбик:
9.05528
1
39
9.0


In [14]:
#Задача 3
q = np.quantile(a_ld[:, 1], 0.75)
a_ld[:, 1] = np.where(a_ld[:, 1] <= q, a_ld[:, 1], q)
print(a_ld)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [15]:
#Задача 4
print(np.count_nonzero(a_ld[:, 1] == 0))
a_ld[:, 1] = np.where(a_ld[:, 1] != 0, a_ld[:, 1], 1)

479


In [16]:
#Задача 5
print(len(np.unique(a_ld[:, 0])))

100000


In [17]:
#Задача 6
print(len(np.unique(a_ld[:, 2])))
print(np.unique(a_ld[:, 2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


In [18]:
#Задача 7
a_ld_2 = a_ld[np.where(a_ld[:, 2] <= 5)]
print(a_ld_2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [19]:
#Задача 8
ingr_1_min = a_ld[:, 2] / a_ld[: ,1]
print(np.max(ingr_1_min))

24.0


In [20]:
#Задача 9
sort0 = np.array(sorted(a_ld, key=lambda a_entry: a_entry[1], reverse=True))
print(np.mean(sort0[:100, 2]))

10.03


In [21]:
#Задача 10
rand = np.random.randint(len(a_ld), size=10)
print(a_ld[rand, :])

[[285961     45      9]
 [317448     65     19]
 [178444     15      5]
 [456744     20      7]
 [ 91884     65      5]
 [161530     15      7]
 [260535     30      5]
 [ 59160     65     12]
 [101304     25      7]
 [ 64869     65      7]]


In [22]:
#Задача 11
print(len(a_ld[np.where(a_ld[:, 2] < np.mean(a_ld[:, 2]))]) / len(a_ld) * 100)

58.802


In [24]:
#Задача 12
prosto = np.c_[a_ld, np.zeros(len(a_ld)).astype(int)]
prosto[:, 3] = np.where((a_ld[:, 1] <= 20) & (a_ld[:, 2] <= 5), 1, 0)
prosto

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

In [25]:
#Задача 13
print(len(prosto[np.where(prosto[:, 3] == 1)]) / len(prosto) * 100)

9.552


In [26]:
#Задача 14
time = np.array([np.zeros(len(a_ld)).astype(int), a_ld[:, 0], prosto[:, 3]]).transpose()
time[:, 0] = np.where((a_ld[:, 1] >= 10) & (a_ld[:, 1] < 20), 1, time[:, 0])
time[:, 0] = np.where(a_ld[:, 1] >= 20, 2, time[:, 0])
time

array([[     2, 127244,      0],
       [     2,  23891,      0],
       [     1,  94746,      0],
       ...,
       [     2, 498432,      0],
       [     0, 370915,      1],
       [     2,  81993,      0]])