# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

a = np.random.uniform(0,20,28).reshape(4,7)
a_rez = (a - np.min(a))/(np.max(a)-np.min(a))
print(a_rez)

[[0.48258925 0.81154479 0.99043018 0.22379202 0.00237084 1.
  0.34957218]
 [0.44988044 0.96655062 0.30147761 0.69025886 0.54904659 0.33123809
  0.53945818]
 [0.5258352  0.48515326 0.47394811 0.14725254 0.97682908 0.
  0.77915344]
 [0.78373333 0.33783688 0.28337952 0.34341279 0.03188148 0.46693672
  0.65136346]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [2]:
import numpy as np
a = np.random.randint(0,10,80).reshape(8,10)
print(min(a.sum(axis=1)))

38


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [3]:
a1 = np.array((0,0,0))
a2 = np.array((3,3,3))
ev = np.sqrt(np.sum(np.square(a2-a1)))
print(ev)

5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [5]:
A = np.array([[-1,2,4], [-3,1,2], [-3,0,1]])
B = np.array([[3,-1], [2,1]])
C = np.array([[7,21], [11,8], [8,4]])
X = np.linalg.inv(A) @ (C*(-1)) @ np.linalg.inv(B)
print(X)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [7]:
import numpy as np

In [8]:
my_file = "/content/minutes_n_ingredients.csv"

In [9]:
#Задача 1
a_ld = np.loadtxt(my_file, int, skiprows=1, delimiter=',')
a_ld[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [10]:
#Задача 2
print("Второй столбик:")
print(np.mean(a_ld[:,1]))
print(np.max(a_ld[:,1]))
print(np.min(a_ld[:,1]))
print(np.median(a_ld[:,1]))
print('----------------------')
print("Третий столбик:")
print(np.mean(a_ld[:, 2]))
print(np.min(a_ld[:, 2]))
print(np.max(a_ld[:, 2]))
print(np.median(a_ld[:, 2]))


Второй столбик:
21601.00169
2147483647
0
40.0
----------------------
Третий столбик:
9.05528
1
39
9.0


In [12]:
#Задача 3
q = np.quantile(a_ld[:, 1], 0.75)
a_ld[:, 1] = np.where(a_ld[:, 1] <= q, a_ld[:, 1], q)
print(a_ld)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [11]:
#Задача 4
print(np.count_nonzero(a_ld[:, 1] == 0))
a_ld[:, 1] = np.where(a_ld[:, 1] != 0, a_ld[:, 1], 1)

479


In [13]:
#Задача 5
print(len(np.unique(a_ld[:, 0])))

100000


In [14]:
#Задача 6
print(len(np.unique(a_ld[:, 2])))
print(np.unique(a_ld[:, 2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


In [15]:
#Задача 7
a_ld_2 = a_ld[np.where(a_ld[:, 2] <= 5)]
print(a_ld_2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [18]:
#Задача 8
ingr_1_min = a_ld[:, 2] / a_ld[: ,1]
print(np.max(ingr_1_min))

24.0


In [19]:
#Задача 9
sort0 = np.array(sorted(a_ld, key=lambda a_entry: a_entry[1], reverse=True))
print(np.mean(sort0[:100, 2]))

10.03


In [20]:
#Задача 10
rand = np.random.randint(len(a_ld), size=10)
print(a_ld[rand, :])

[[ 82617     55      7]
 [181276      5      6]
 [ 82779     65     15]
 [429453     65     15]
 [457963     20      6]
 [155200     65     16]
 [150909      5      4]
 [302110     50     12]
 [433269     50      8]
 [334658     65      8]]


In [21]:
#Задача 11
print(len(a_ld[np.where(a_ld[:, 2] < np.mean(a_ld[:, 2]))]) / len(a_ld) * 100)

58.802


In [22]:
#Задача 12
prosto = np.c_[a_ld, np.zeros(len(a_ld)).astype(int)]
prosto[:, 3] = np.where((a_ld[:, 1] <= 20) & (a_ld[:, 2] <= 5), 1, 0)
prosto

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

In [23]:
#Задача 13
print(len(prosto[np.where(prosto[:, 3] == 1)]) / len(prosto) * 100)

9.552


In [24]:
#Задача 14
time = min(len(a[np.where((a[:,1]<=10))]), len(a[np.where((a[:,1]>10) & (a[:,1]<20))]), len(a[np.where((a[:,1]>=20))]))
a = np.arange(time*3*3).reshape(3,time,3)
a[0,:,:] = a[np.where((a[:,1]<=10))][:time]
a[1,:,:] = a[np.where((a[:,1]>10) & (a[:,1]<20))][:time]
a[2,:,:] = a[np.where((a[:,1]>=20))][:time]
print(a)


IndexError: ignored